// <auto-generated />
using System;
using LRP_Project_Vize_MedineSarımustafaoğlu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LRP_Project_Vize_MedineSarımustafaoğlu.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511171701_UpdateUserComputerRelation")]
    partial class UpdateUserComputerRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LRP_Project_Vize_MedineSarımustafaoğlu.Models.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LabId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ram")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Specs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LabId");

                    b.HasIndex("StudentId");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("LRP_Project_Vize_MedineSarımustafaoğlu.Models.Lab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Labs");
                });

            modelBuilder.Entity("LRP_Project_Vize_MedineSarımustafaoğlu.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LRP_Project_Vize_MedineSarımustafaoğlu.Models.Computer", b =>
                {
                    b.HasOne("LRP_Project_Vize_MedineSarımustafaoğlu.Models.Lab", "Lab")
                        .WithMany()
                        .HasForeignKey("LabId");

                    b.HasOne("LRP_Project_Vize_MedineSarımustafaoğlu.Models.User", "Student")
                        .WithMany("Computers")
                        .HasForeignKey("StudentId");

                    b.Navigation("Lab");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LRP_Project_Vize_MedineSarımustafaoğlu.Models.User", b =>
                {
                    b.Navigation("Computers");
                });
#pragma warning restore 612, 618
        }
    }
}
